language: rust
cache: cargo

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --locked
  - cargo test --locked
  - ls -la $TRAVIS_BUILD_DIR/target/release/dssim
  - cp ./target/release/dssim ./$TRAVIS_OS_NAME-dssim

deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  overwrite: true
  skip_cleanup: true
  api_key: $github_token
  file_glob: true
  file:
    - $TRAVIS_BUILD_DIR/linux-dssim
    - $TRAVIS_BUILD_DIR/osx-dssim
  on:
    tags: true
